#    ________      __          __   _  __
#   / ____/ /___  / /_  ____ _/ /  | |/ /
#  / / __/ / __ \\/ __ \\/ __ `/ /   |   /
# / /_/ / / /_/ / /_/ / /_/ / /   /   |
# \\____/_/\\____/_.___/\\__,_/_/   /_/|_|
#
# Main Config


HoverAndClickText:
  Enable: true
  Text: "&7&oClick to go!"
  Command: "/send %player% %target%"

GlobalChatPrefix:
  Enable: true
  Prefix: "!"