#    ________      __          __   _  __
#   / ____/ /___  / /_  ____ _/ /  | |/ /
#  / / __/ / __ \\/ __ \\/ __ `/ /   |   /
# / /_/ / / /_/ / /_/ / /_/ / /   /   |
# \\____/_/\\____/_.___/\\__,_/_/   /_/|_|
#
# Main Config

HoverAndClickText:
  Enable: true
  Text: "&7&oClick to go!"
  Command: "/send %player% %target%"

GlobalChatPrefix:
  Enable: true
  Prefix: "!"

UsePrivateMessaging: true

AllowConsolePrivateMessaging:
  Sending: true
  Receiving: true

ConversationsAutoDelete: 30 # Seconds after last activity

ServerGroups:
  pvp:
    servers: ["kitpvp", "bedwars"]
    permission-required: "globalx.globalchat.servergroup.pvp"
  survival:
    servers: ["survival", "skyblock"]
    permission-required: "globalx.globalchat.servergroup.survival"
  farming:
    servers: ["skyprison"]
    permission-required: "globalx.globalchat.servergroups.farming"
  lobbies:
    servers: ["lobby"] # ["lobby-1", "lobby-2"]
    permission-required: "none"
  # Add more server groups here if needed

#
# NOTE: The Group List has priority based on the position of
# the group. E.g. The "Owner" group is in position 0 (max priority)
#
Groups:
  Owner:
    Prefix: "&4&lOWNER &4"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.owner"
    ChatPrefixes: ["%defaultPrefix%ow", "!"]
  Manager:
    Prefix: "&c&lMANAGER &c"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.manager"
    ChatPrefixes: ["%defaultPrefix%mngr", "!"]
  SrAdmin:
    Prefix: "&c&lSRADMIN &c"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.sradmin"
    ChatPrefixes: ["%defaultPrefix%srad", "!"]
  Admin:
    Prefix: "&c&lADMIN &c"
    CoolDown: 0
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.admin"
    ChatPrefixes: ["%defaultPrefix%ad", "!"]
  Youtuber:
    Prefix: "&c&lYOUTUBER &c"
    CoolDown: 10
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.youtuber"
    ChatPrefixes: ["global:"]
  Streamer:
    Prefix: "&5&lSTREAMER &5"
    CoolDown: 10
    ChatFormat: "%prefix% %serverNameFormat% - %player_prefix%%player_name% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.streamer"
    ChatPrefixes: ["global:"]
  Anon:
    Prefix: "&7&lANON &7"
    CoolDown: 10
    ChatFormat: "%prefix% %player_prefix% &r&7- &f%message%"
    Permission: "globalx.globalchat.use.anon"
    ChatPrefixes: ["global:"]
  # Add more groups here if needed

ScheduledMessages:
  DiscordServer:
    Message: "\n%prefix% &fRemember to join our Discord Server at &9dsc.gg/globalx-discord\n"
    Timeout: 300 # 5 minutes in seconds
    Repeat: true
    Servers: ["*"] # All servers
    Action: "OPEN_URL" # "RUN_COMMAND", "OPEN_FILE", "SUGGEST_COMMAND", "CHANGE_PAGE", "OPEN_URL"
    Value: "https://dsc.gg/globalx-discord"
    Hover: "Click to join our discord server!"
  Reviews:
    Message: "\n%prefix% &fLeave a &e5-star review &fon our plugin\n"
    Timeout: 120
    Repeat: true
    Servers: ["*"] # All servers
    Action: "OPEN_URL"
    Value: "https://www.spigotmc.org/resources/⭐-globalx-easiest-globalchat-plugin-on-spigotmc.102941/reviews#review-0"
    Hover: "Click to leave a review!"
  # Add more scheduled messages here if needed
